[#1180] Update admin team section in `/help/how.html.erb`
mysociety/whatdotheyknow-theme pull request #1374
Opened 2022-08-26 13:56 UTC by mdeuk

## Relevant issue(s)
Fixes #1180

## What does this do?
This updates the content of section "Membership of the admin team" based on the agreed text.

## Why was this needed?
Improvements being made as part of the implementation of the volunteer plan and have been ratified by the Service Manager and team.

## Implementation notes
`/lib/views/help/how.html.erb` has mixed use of ' and ’ (U+2019) - the latter being the predominant. As this is what's already there, I haven't sought to revise any existing content. We can do that at another point.

## Screenshots
N/A

## Notes to reviewer
N/A

2022-08-28 13:10 UTC, confirmordeny requested changes
Should we be saying "we keep in touch with you by email"? - it implies the reader is or will be a volunteer.

2022-08-28 13:22 UTC, mdeuk commented
> Should we be saying "we keep in touch with you by email"? - it implies the reader is or will be a volunteer.

This is a good point - we have deviated slightly from what the original text said:

> As mySociety is a distributed organisation, this happens via the monthly WhatDoTheyKnow volunteer catchup calls, and by email or individual calls as required. 

I suppose it is a bit of scene-setting, and the removal of the "catchup calls" part is not of particular significance as it is addressed in the next paragraph.

If we were to re-write this part, what might you suggest as a suitable replacement?

2022-08-31 11:02 UTC, garethrees commented
> If we were to re-write this part, what might you suggest as a suitable replacement?

How about: "As mySociety is a distributed organisation, we keep in touch ~with you~ by email or individual calls as required."

2022-08-31 11:05 UTC, mdeuk commented
> How about: "As mySociety is a distributed organisation, we keep in touch ~with you~ by email or individual calls as required."

That _**seems**_ like a reasonable alternative. 

Are we ok holding off merging this until @sallytay is back and can give a +1?

2022-08-31 11:08 UTC, garethrees commented
Yeah would be good for Sally to review – I haven't followed this one closely.

2022-09-28 13:17 UTC, sallytay approved these changes

2022-09-28 13:41 UTC, mdeuk commented
@sallytay just a quick query: is this ticket being approved _as is_, or with the modification suggested in https://github.com/mysociety/whatdotheyknow-theme/pull/1374#issuecomment-1232789021? If it's the latter we'll need a patch to modify this - it's a trivial thing that should just take a minute to push.

2022-09-28 13:43 UTC, sallytay commented
Sorry I didn't make that clear. yes with the modification suggested in #1374 (comment)

2022-10-20 11:50 UTC, merged