fixing a link in the glossary
mysociety/whatdotheyknow-theme pull request #1523
Opened 2022-11-26 18:36 UTC by confirmordeny

fixing a link in the glossary

## Relevant issue(s)
See above.

## What does this do?
See above.

## Why was this needed?
See above.

## Implementation notes
N/A.

## Screenshots
N/A.

## Notes to reviewer
N/A.

2022-12-14 17:22 UTC, garethrees requested changes
e3d4b92edcb099399add100ea7852fe71e1c9c9b looks good in general, but looks like it may still have one broken link

2022-12-14 17:22 UTC, garethrees commented on lib/views/help/glossary.html.erb
> + orities">public authorities</a> can take the identity of the requester into account in certain situations e.g. when applying the <a href="#cost_limit">cost limit</a>.</dd>
Doesn't look like this should have newlines breaking the href?

2022-12-14 17:23 UTC, garethrees commented on lib/views/help/glossary.html.erb
> + orities">public authorities</a> can take the identity of the requester into account in certain situations e.g. when applying the <a href="#cost_limit">cost limit</a>.</dd>
Also, think it needs the same change from `#public_authorities` to `#public_authority`.

2023-02-01 12:29 UTC, gbp approved these changes

2023-02-01 12:34 UTC, merged