Disclosure log Help Officers page
mysociety/whatdotheyknow-theme pull request #1729
Opened 2023-06-28 13:24 UTC by lucascumsille

## Relevant issue(s)
Fixes: https://github.com/mysociety/whatdotheyknow-theme/issues/1688

## What does this do?
Includes the disclosure log SW in the help/officers page and improves spacing left side bar.

## Notes to reviewer

This PR has two commits:

### First one add the disclosure log to the help/officers page

Is the position alright @garethrees? and let me know if you like styling. I'm kind of reusing what we currently have for the research section, but I added some extra styling.
<img width="1901" alt="Screenshot 2023-06-28 at 14 11 05" src="https://github.com/mysociety/whatdotheyknow-theme/assets/13790153/d4098991-1751-4fa9-89a0-0483c9b99094">

### Second commit
It's optional, but working on this ticket I noticed that the `li` elements on the sidebar are too close to each other, so I added margin bottom. Let me know if you want to drop this commit.

2023-06-28 14:12 UTC, garethrees requested changes

2023-06-28 14:12 UTC, garethrees commented on lib/views/help/officers.html.erb
> +  <div class="article-grid__item with-background">
This looks great, but would position at the bottom of the page

![Screenshot 2023-06-28 at 15 10 08](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/cb9c376c-99e6-4f14-b5b3-8c81ea234131)

2023-06-28 14:12 UTC, garethrees commented on app/assets/stylesheets/responsive/custom.scss
> +
Ordinarily I'd suggest a separate pull request for completely orthogonal commits, but since it's here then let's just stick with it 👍

2023-06-29 05:26 UTC, lucascumsille commented
Thanks @garethrees I'm glad you like it =)
I just moved the section down below. 

<img width="1431" alt="Screenshot 2023-06-29 at 06 24 21" src="https://github.com/mysociety/whatdotheyknow-theme/assets/13790153/ca5fecde-7f12-4ed6-997a-cff5c46794e3">

2023-07-03 10:30 UTC, garethrees approved these changes

2023-07-03 10:31 UTC, merged