Set Reply-To for data breach emails.
mysociety/whatdotheyknow-theme pull request #1768
Opened 2023-08-09 16:57 UTC by dracos

Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1767

2023-08-09 17:26 UTC, chrismytton requested changes

2023-08-09 17:26 UTC, chrismytton commented on lib/data_breach.rb
> +      set_reply_to_headers(nil, 'Reply-To' => report.contact_email)
The `contact_email` field is optional, so we won't necessarily have an email address in `report.contact_email`.

We might also have a `logged_in_user`, so perhaps want to pass in the `logged_in_user` as the first argument, and then if there's an email address in `contact_email`, pass that in as the reply-to header?

Not sure exactly how the blackhole stuff works inside `set_reply_to_headers`, @gbp may be able to give more detailed guidance 🙂

2023-08-10 14:24 UTC, chrismytton commented on lib/data_breach.rb
> +      set_reply_to_headers(nil, 'Reply-To' => report.contact_email)
Yes on reflection I think you're right, best to leave the logged in user out of this.

2023-08-14 10:56 UTC, chrismytton approved these changes

2023-08-25 08:50 UTC, merged

2023-08-25 08:51 UTC, garethrees commented
Thanks both!