More links on authority pages etc
mysociety/whatdotheyknow-theme pull request #1828
Opened 2024-01-29 07:54 UTC by confirmordeny

## Relevant issue(s)
This would add more links to some of the authority pages if the relevant tags are present.

(1) Research Organization Registry (ROR) - https://ror.org/ - based on "ror:" tag.
(2) London Stock Exchange - https://www.londonstockexchange.com/ - based on "lon:" tag.

Also, there is a minor wording correction to a help page.

## What does this do?
See above.

## Why was this needed?
See above.

## Implementation notes
N/A.

## Screenshots
N/A.

## Notes to reviewer
See above.

2024-02-05 11:07 UTC, gbp commented on lib/views/public_body/_more_info.html.erb
> +                    "https://www.londonstockexchange.com/stock/#{ tag_value }"/company-page %><br>
```suggestion
                    "https://www.londonstockexchange.com/stock/#{ tag_value }/company-page" %><br>
```

2024-02-05 11:08 UTC, gbp requested changes
Thanks for this. One minor change which I can make when merging.

2024-02-09 12:08 UTC, gbp commented
Merged in 3a540da

2024-02-09 12:08 UTC, closed without merging

2024-02-09 19:57 UTC, confirmordeny commented
Thank you.